name: Integration Tests

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed
  workflow_dispatch:

jobs:
  integration-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    needs: []
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider: [SqlServer, MySql, PostgreSql]
    env:
      DatabaseProvider: ${{ matrix.provider }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore FilterBuilder.sln

      - name: Build
        run: dotnet build FilterBuilder.sln --no-restore --configuration Release

      - name: Run integration tests for ${{ matrix.provider }}
        run: dotnet test test/Q.FilterBuilder.IntegrationTests/Q.FilterBuilder.IntegrationTests.csproj --no-build --configuration Release --logger trx
